semantics:
  - signature: "android.text.TextUtils.isEmpty:boolean(java.lang.String)"
    flow: "1->-1"
  
  - signature: "org.apache.http.HttpResponse.getStatusLine:org.apache.http.StatusLine()"
    flow: "0->0"
    
  - signature: "org.apache.http.StatusLine.getStatusCode:boolean()"

  